module.exports = {
  footerText: "© 2020 NNB",
  CORS: [],
  apiPrefix: "/api",
  openPages: [
    "/home",
    "/about",
    "/services",
    "/blog",
    "/gallery",
    "/fleet",
    "/blog",
    "/tracking",
    "/contact",
    "/news/",
    "/service/",
  ],
  adminPages: [
    "/main/dashboard",
    "/main/suggestion-and-question",
    "/main/clients",
    "/main/client/",
    "/hr/resume",
    "/hr/staffs",
    "/settings/certificate",
    "/settings/gallery",
    "/settings/fleet",
    "/settings/vacancy",
    "/settings/services",
    "/settings/news",
    "/settings/dictionary/position-type",
    "/settings/dictionary/country",
    "/settings/dictionary/region",
    "/settings/dictionary/district",
    "/settings/profile/info",
    "/settings/profile/password",
    "/settings/moderators",
  ],
  moderatorPages: [
    "/main/dashboard",
    "/main/suggestion-and-question",
    "/main/clients",
    "/main/client/",
    "/hr/resume",
    "/hr/staffs",
    "/settings/certificate",
    "/settings/gallery",
    "/settings/fleet",
    "/settings/vacancy",
    "/settings/services",
    "/settings/news",
    "/settings/dictionary/position-type",
    "/settings/dictionary/country",
    "/settings/dictionary/region",
    "/settings/dictionary/district",
    "/settings/profile/info",
    "/settings/profile/password",
    "/settings/moderators",
  ],
  locales: [
    {
      languageId: "nameEn",
      locale: "en",
      name: "English",
      icon: "us",
    },
    {
      languageId: "nameRu",
      locale: "ru",
      name: "Русский",
      icon: "ru",
    },
    {
      languageId: "nameUz",
      locale: "uz",
      name: "O'zbek",
      icon: "uz",
    },
  ],
};
