const apiUrl = {
  signUp: "POST /auth/register",
  signIn: "POST /auth/login",
  userMe: "/user/me",
  userCheckPhone: "POST /user/checkPhone",
  checkUser: "POST /user/checkUser",
  register: "POST /user",
  searchUser: "POST /user/search",
  getUsers: "/user",
  getUser: "/user",
  getByPhone: "/user/getByPhone",
  editUser: "PUT /user",
  editPassword: "PUT /user/changePassword",
  setPassword: "PUT /user/setPassword",
  getMenus: "/menus",

  postCurrentUserInfoEdit: "PUT /user/editMe",
  postCurrentPasswordEdit: "user/edit/pass",

  getCountry: "/country",
  postCountry: "POST /country",
  deleteCountry: "DELETE /country",
  searchCountry: "POST /universal/country/search",
  getCountryList: "GET /universal/country/list",

  getRegion: "/region",
  getRegionList: "/region/list",
  postRegion: "POST /region",
  deleteRegion: "DELETE /region",
  searchRegion: "POST /region/search",

  getDistrict: "/district",
  getDistrictList: "/district/list",
  postDistrict: "POST /district",
  deleteDistrict: "DELETE /district",
  searchDistrict: "POST /district/search",
  getDistrictByRegionId: "/district/distByRegion",

  getPositionType: "/position-type",
  postPositionType: "POST /position-type",
  deletePositionType: "DELETE /position-type",
  searchPositionType: "POST /universal/position-type/search",

  getStaff: "/staffs",
  postStaff: "POST /staff",
  putStaff: "PUT /staff",
  deleteStaff: "DELETE /staff",
  searchStaff: "POST /staff/search",
  postIsActiveStaff: "POST /staff/active",

  postCertificate: "POST /certificate",
  getCertificate: "/certificates",
  putCertificate: "PUT /certificate",
  deleteCertificate: "DELETE /certificate",

  postGallery: "POST /gallery",
  getGallery: "/gallery",
  putGallery: "PUT /gallery",
  deleteGallery: "DELETE /gallery",

  postFleet: "POST /fleet",
  getFleet: "/fleet",
  putFleet: "PUT /fleet",
  deleteFleet: "DELETE /fleet",

  postVacancy: "POST /vacancy",
  getVacancy: "/vacancies",
  putVacancy: "PUT /vacancy",
  putVacancyView: "/vacancy/update-view",
  deleteVacancy: "DELETE /vacancy",

  postService: "POST /service",
  getService: "/services",
  putService: "PUT /service",
  deleteService: "DELETE /service",

  postNews: "POST /news",
  getNews: "/news",
  putNews: "PUT /news",
  deleteNews: "DELETE /news",
  searchNews: "POST /news/search",
  postIsActiveNews: "POST /news/active",

  postModerator: "POST /user/addModerator",
  getModerator: "/user/getModerator",
  putModerator: "PUT /user",
  deleteModerator: "DELETE /user",

  getSuggestionAndQuestion: "/universal/suggestion-and-question-list",
  postSuggestionAndQuestion: "POST /suggessions",
  putSuggestionAndQuestion: "/universal/updateStatusSuggestionAndQuestion",
  deleteSuggestionAndQuestion: "DELETE /suggestion-and-question",

  getResume: "/resume",
  postResume: "POST /resume",
  putResume: "PUT /resume",
  deleteResume: "DELETE /resume",

  getClient: "/client",
  getClientFile: "/client/file",
  getClientFinish: "/client/finish",
  postClient: "POST /client",
  putClient: "PUT /client",
  deleteClient: "DELETE /client",
  getClientPoint: "POST /client/points",
  postClientPoint: "POST /client/point",
  putClientPoint: "PUT /client/point",
  searchClient: "POST /client/search",
};
export default apiUrl;
