export  default [
    {id:1,parentId:null,type:'group',nameEn:'Main',nameRu:'Главный',nameUz:'Asosiy',icon:null,route:null,active:true,roleName:'ROLE_ADMIN'},
    {id:2,parentId:1,type:'item',nameEn:'Dashboard',nameRu:'Панель инструментов',nameUz:'Uskunalar paneli',icon:'dasbhoard',route:'/main/dashboard',active:true,role:'ROLE_ADMIN'},
    {id:3,parentId:1,type:'item',nameEn:'Suggestion and Question',nameRu:'Предложение и вопрос',nameUz:'Taklif va savol',icon:'feedback',route:'/main/suggestion-and-question',active:true,role:'ROLE_ADMIN'},
    {id:4,parentId:1,type:'item',nameEn:'Clients',nameRu:'Клиенты',nameUz:'Mijozlar',icon:'shopping-cart',route:'/main/clients',active:true,role:'ROLE_ADMIN'},
    {id:5,parentId:null,type:'group',nameEn:'Management Department',nameRu:'Отдел управления',nameUz:'Boshqaruv bo\'limi',icon:null,route:null,active:true,role:'ROLE_ADMIN'},
    {id:6,parentId:5,type:'item',nameEn:'Staffs',nameRu:'Сотрудники',nameUz:'Xodimlar',icon:'contacts',route:'/hr/staffs',active:true,role:'ROLE_ADMIN'},
    {id:7,parentId:5,type:'item',nameEn:'Resume',nameRu:'Резюме',nameUz:'Rezyume',icon:'auth-screen',route:'/hr/resume',active:true,role:'ROLE_ADMIN'},
    {id:8,parentId:null,type:'group',nameEn:'Settings',nameRu:'Настройки',nameUz:'Sozlamalar',icon:null,route:null,active:true,role:'ROLE_ADMIN'},
    {id:9,parentId:8,type:'item',nameEn:'Vacancies',nameRu:'Вакансии',nameUz:'Bo\'sh ish o\'rinlari',icon:'table',route:'/settings/vacancy',active:true,role:'ROLE_ADMIN'},
    {id:10,parentId:8,type:'item',nameEn:'Certificates',nameRu:'Сертификаты',nameUz:'Sertifikatlar',icon:'editor',route:'/settings/certificate',active:true,role:'ROLE_ADMIN'},
    {id:11,parentId:8,type:'item',nameEn:'Gallery',nameRu:'Галерея',nameUz:'Galereya',icon:'editor',route:'/settings/gallery',active:true,role:'ROLE_ADMIN'},
    {id:12,parentId:8,type:'item',nameEn:'Fleet',nameRu:'Флот',nameUz:'Filo',icon:'editor',route:'/settings/fleet',active:true,role:'ROLE_ADMIN'},
    {id:13,parentId:8,type:'item',nameEn:'Services',nameRu:'Сервисы',nameUz:'Xizmatlar',icon:'crm',route:'/settings/services',active:true,role:'ROLE_ADMIN'},
    {id:14,parentId:8,type:'item',nameEn:'News',nameRu:'Новости',nameUz:'Yangiliklar',icon:'copy',route:'/settings/news',active:true,role:'ROLE_ADMIN'},
    {id:15,parentId:8,type:'item',nameEn:'Moderators',nameRu:'Модераторы',nameUz:'Moderatorlar',icon:'avatar',route:'/settings/moderators',active:true,role:'ROLE_ADMIN'},
    {id:16,parentId:8,type:'collapse',nameEn:'Profile',nameRu:'Профиль',nameUz:'Profil',icon:'profile2',route:'/settings/profile',active:true,role:'ROLE_ADMIN'},
    {id:17,parentId:16,type:'item',nameEn:'My Info',nameRu:'Мой информации',nameUz:'Mening ma\'lumotlarim',icon:'circle-o',route:'/settings/profile/info',active:true,role:'ROLE_ADMIN'},
    {id:18,parentId:16,type:'item',nameEn:'My Password',nameRu:'Мой пароль',nameUz:'Mening parolim',icon:'circle-o',route:'/settings/profile/password',active:true,role:'ROLE_ADMIN'},
    {id:19,parentId:8,type:'collapse',nameEn:'Reference',nameRu:'Справочник',nameUz:'Ma\'lumotnoma',icon:'apps',route:'/settings/dictionary',active:true,role:'ROLE_ADMIN'},
    {id:20,parentId:19,type:'item',nameEn:'Position type',nameRu:'Тип должность',nameUz:'Lavozim turi',icon:'circle-o',route:'/settings/dictionary/position-type',active:true,role:'ROLE_ADMIN'},
    {id:21,parentId:19,type:'item',nameEn:'Country',nameRu:'Страна',nameUz:'Davlatlar',icon:'circle-o',route:'/settings/dictionary/country',active:true,role:'ROLE_ADMIN'},
    {id:22,parentId:19,type:'item',nameEn:'Regions',nameRu:'Регионы',nameUz:'Viloyatlar',icon:'circle-o',route:'/settings/dictionary/region',active:true,role:'ROLE_ADMIN'},
    {id:23,parentId:19,type:'item',nameEn:'Districts',nameRu:'Районы',nameUz:'Tumanlar',icon:'circle-o',route:'/settings/dictionary/district',active:true,role:'ROLE_ADMIN'}
];
